version: "3.3"

services:

  flask:
    build: ./web
    container_name: web
    restart: always
    expose:
      - 8087
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask


  db:
    build: ./postgres
    container_name: postgres
    env_file:
      - env_file
    restart: always
    ports:
      - "5432:5432"
    
volumes:
  dbdata: